# Generated by Django 2.0 on 2011-11-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Assetsname', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('Details', models.CharField(max_length=50)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetsCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_Title', models.CharField(max_length=50)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetssubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcat_Title', models.CharField(max_length=50)),
                ('Assets_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AssetsCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_No', models.CharField(max_length=50)),
                ('Floor', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='Assets_SubCategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AssetssubCategory'),
        ),
        migrations.AddField(
            model_name='assets',
            name='Room_No_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Rooms'),
        ),
    ]
