# Generated by Django 2.0 on 2022-06-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetssubcategory',
            name='subcat_image',
            field=models.ImageField(default='default.jpeg', upload_to='images/'),
        ),
    ]
