# Generated by Django 2.0 on 2011-11-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_assetssubcategory_subcat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetssubcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
