# Generated by Django 2.0 on 2022-06-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20111109_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetssubcategory',
            name='subcat_image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
