# Generated by Django 2.0 on 2022-06-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220627_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetssubcategory',
            name='subcat_image',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
