# Generated by Django 2.0 on 2022-06-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220627_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetssubcategory',
            name='subcat_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
