# Generated by Django 2.0 on 2022-06-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220630_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetssubcategory',
            name='subcat_image',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
