# Generated by Django 2.0 on 2011-11-08 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_assetssubsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='AssetsSubsubCategory_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.AssetsSubsubCategory'),
        ),
    ]
